# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnimaisDomesticos',
            new_name='AnimalDomestico',
        ),
        migrations.RenameModel(
            old_name='Doencas',
            new_name='Doenca',
        ),
        migrations.RenameModel(
            old_name='GruposComunitarios',
            new_name='GrupoComunitario',
        ),
        migrations.RenameModel(
            old_name='MeiosComunicacao',
            new_name='MeioComunicacao',
        ),
    ]
