# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animaldomestico',
            old_name='outros_animais',
            new_name='especie',
        ),
        migrations.RemoveField(
            model_name='animaldomestico',
            name='cao',
        ),
        migrations.RemoveField(
            model_name='animaldomestico',
            name='gato',
        ),
        migrations.RemoveField(
            model_name='familia_animal',
            name='especie',
        ),
    ]
