# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20170710_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia_eletrodomestico',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='familia_meiocomunicacao',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='familia_transporte',
            name='nome',
        ),
    ]
